| Mitigation Number | Threats Mitigating  | Mitigation                                                                                                                                                                                                                                                                    |
| ----------------- | ------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| M-001             | T01                 | Use HashiCorp Vault to store the Stripe keys, and fetch them at runtime.                                                                                                                                                                                                      |
| M-002             | T02                 | As part of our SAST scans, ensure the CI/CD pipeline fetches the Stripe keys that will be deployed and checks the prefix for live and test versions.<br><br>Test keys are prefixed with:<br>pk_test<br>sk_test<br><br>Live keys are prefixed with:<br>pk_live<br>sk_live<br><br> |
| M-003             | T04                 | Pin npm packages to specific versions, and perform regular scans in our CI/CD pipelines.                                                                                                                                                                                      |
| M-004             | T03                 | Leverage the Subresource Integrity (SRI) security feature to ensure the cryptographic hash of a fetched resource matches the expected hash.                                                                                                                                    |
| M-005             | T01                 | Set IP restrictions on the Stripe keys to only allow the IP addresses of our servers from the Stripe management web portal.                                                                                                                                                    |
| M-006             | T01                 | Implement role-based access control (RBAC) and audit logs to monitor and restrict who can access the Stripe API keys.                                                                                                                                                         |
| M-007             | T05            | Use the Stripe verification library to validate that webhook events originate from Stripe.<br><br>More details at: [Stripe Webhooks Documentation](https://docs.stripe.com/webhooks)                                                                                          |
| M-008             | T06                 | Handle duplicate events by making the app idempotent to ensure the same signed Stripe request cannot be replayed multiple times.                                                                                                                                               |
| M-009             | T10                 | Ensure all transactions are timestamped and logged, and save the last few characters returned by Stripe for each transaction. Note that logging is a significant topic in e-commerce that deserves its own write-up.                                                           |
| M-010             | T05           | Configure the webserver to block requests to the webhook process that are not received from Stripe IP addresses listed in the [Stripe Webhooks Documentation](https://docs.stripe.com/webhooks#verify-manually-1).                                                             |
| M-011             | T02                 | Leverage a DAST scan with the Stripe key used in production to ensure Stripe test cards cannot perform purchases in production.                                                                                                                                                |
| M-012             | T07                 | In the add coupon functionality, ensure checks are implemented at multiple locations in the code, for example, during the add coupon operation and again during the checkout operation to verify the number of coupons used.                                                   |
| M-013             | T07                 | In the add coupon functionality, ensure checking operations and counter incrementing operations are performed before the coupon is applied.                                                                                                                                    |
| M-014             | T08                 | During the checkout process, copy the user's cart (cache the current cart) and use the cached version for all operations afterwards.                                                                                                                                           |
| M-015             | T07            | During the checkout process, copy the user's coupons (cache the current coupons used) and use the cached version for all operations afterwards.                                                                                                                                |
| M-016             | T07, T08            | Leverage database locks and concurrency features to mitigate race conditions.                                                                                                                                                                                                 |
| M-017             | T09                 | Ensure TLS is enforced in production and that industry-standard secure ciphers are in use.                                                                                                                                                                                     |


